version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: badgery-dev
    volumes:
      - .:/app # Mount source code
      - node_modules:/app/node_modules # Use named volume for node_modules
      - .env.development:/app/.env.development:ro # Mount development env file as read-only
    ports:
      - "3000:3000" # Main application port
      - "5173:5173" # Vite dev server port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
      - REMIX_DEV_SERVER_PORT=5173
      - CHOKIDAR_USEPOLLING=true # Helpful for certain systems to detect file changes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - badgery-network
    command: npm run dev -- --host

networks:
  badgery-network:
    driver: bridge

volumes:
  node_modules:

